
import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alu20493243j
 */
public class NextPiecePanel extends javax.swing.JPanel {

    private Shape shape;
    /**
     * Creates new form NextPiecePanel
     */
    public NextPiecePanel() {
        initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (shape!=null)
        shape.draw(g, 1, 1, squareWidth(), squareHeight());
    }
    
    public void clearShape()
    {
        shape=null;
    }

    public Shape getShape()
    {
        return shape;
    }
    
    public void setShape(Shape newShape)
    {
        newShape=shape;
    }
    
    public void generateNewShape()
    {
        shape=Shape.getRandomShape();
        repaint();
    }
    private int squareWidth() {
        return getWidth() / 4;
    }
    
    private int squareHeight() {
        return getHeight() / 4;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
