
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alu20493243j
 */
public class RecordsDialog extends javax.swing.JDialog {
    
    private class Record
    {
        public int record;
        public String name;
        
        public Record(int record, String name)
        {
            this.record=record;
            this.name=name;
        }
    }

    private int score;
    private int minRecord;
    private JLabel[] recordLabels;
    private InputStream file=getClass().getResourceAsStream("/High Scores.wav");
    private static final String FILE_NAME="records.csv";
    private ArrayList<Record> listOfRecords;
    /**
     * Creates new form RecordsDialog
     */
    public RecordsDialog(java.awt.Frame parent, boolean modal, int score) {
        super(parent,modal);
        initComponents();
        this.score=score;
        listOfRecords=new ArrayList<Record>();
        initRecordLabels();
        minRecord=0;
        try
        {
            readRecords();
        }
        catch (IOException ex)
        {
            ex.printStackTrace();
        }  
        processRecord();
    }
    public void processRecord()
    {
        jLabelScore.setText("Your Score: "+score);
        if (score<=minRecord)
        {
            jLabelName.setVisible(false);
            jTextFieldName.setVisible(false);
        }
    }

    private void readRecords() throws IOException
    {
        BufferedReader input = null;
        
        
        try
        {
            input = new BufferedReader(new FileReader(FILE_NAME));
            int lineCount=0;
            String line;
            String[] lineRecords=null;
            while(((line=input.readLine()) != null) && lineCount<5)
            {
                lineRecords= line.split(",");
                recordLabels[lineCount].setText(lineRecords[0]+": "+lineRecords[1]);
                lineCount++;
                listOfRecords.add(new Record(Integer.parseInt(lineRecords[0]), lineRecords[1]));
            }
            if(lineCount > 0)
            {
                try
                {
                    minRecord=Integer.parseInt(lineRecords[0]);
                }
                catch(NumberFormatException e)
                {
                    e.printStackTrace();
                }
            }
        }
        
        
        finally
        {
            if(input !=null)
                input.close();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRecord1 = new javax.swing.JLabel();
        jLabelRecord2 = new javax.swing.JLabel();
        jLabelRecord3 = new javax.swing.JLabel();
        jLabelRecord4 = new javax.swing.JLabel();
        jLabelRecord5 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jLabelScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(263, 227));
        setResizable(false);

        jLabelRecord1.setText("0: None");

        jLabelRecord2.setText("0: None");

        jLabelRecord3.setText("0: None");

        jLabelRecord4.setText("0: None");

        jLabelRecord5.setText("0: None");

        jLabelName.setText("Name:");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelScore.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRecord1)
                            .addComponent(jLabelRecord2)
                            .addComponent(jLabelRecord3)
                            .addComponent(jLabelRecord4)
                            .addComponent(jLabelRecord5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addGap(56, 56, 56)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelScore))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRecord1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRecord2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRecord3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRecord4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRecord5)
                .addGap(33, 33, 33)
                .addComponent(jLabelScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        if(score>minRecord)
        {
            try
            {
                saveRecord();
                dispose();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        else
        {
            dispose();
        }
        
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void saveRecord()
    {
        PrintWriter output = null;
        int lineCounter=0;
        boolean saved=false;
        try
        {
            output= new PrintWriter(new FileWriter(FILE_NAME));
            for(Record record: listOfRecords)
            {
                if(score>=record.record && !saved)
                {
                    output.println(score+", "+jTextFieldName.getText());
                    saved=true;
                    lineCounter++;
                }
                if(lineCounter<5)
                {
                    output.println(record.record+", "+record.name);
                    lineCounter++;
                }
                
            }
            if(!saved || lineCounter <5)
            {
                output.println(score+","+jTextFieldName.getText());
            }
        }
        catch (IOException ex) 
        {
            Logger.getLogger(RecordsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }        
        finally
        {
            if(output!=null)
            {
                output.close();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    private void initRecordLabels()
    {
        recordLabels = new JLabel[5];
        recordLabels[0]=jLabelRecord1;
        recordLabels[1]=jLabelRecord2;
        recordLabels[2]=jLabelRecord3;
        recordLabels[3]=jLabelRecord4;
        recordLabels[4]=jLabelRecord5;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRecord1;
    private javax.swing.JLabel jLabelRecord2;
    private javax.swing.JLabel jLabelRecord3;
    private javax.swing.JLabel jLabelRecord4;
    private javax.swing.JLabel jLabelRecord5;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
